-- Run this in Supabase SQL Editor.

create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  streak integer not null default 0,
  total_done integer not null default 0,
  last_done_date date,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  due_date date not null,
  created_at timestamptz not null default now()
);

alter table public.habits enable row level security;
alter table public.reminders enable row level security;

drop policy if exists "habits_select_own" on public.habits;
drop policy if exists "habits_insert_own" on public.habits;
drop policy if exists "habits_update_own" on public.habits;
drop policy if exists "habits_delete_own" on public.habits;

create policy "habits_select_own"
  on public.habits
  for select
  using (auth.uid() = user_id);

create policy "habits_insert_own"
  on public.habits
  for insert
  with check (auth.uid() = user_id);

create policy "habits_update_own"
  on public.habits
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "habits_delete_own"
  on public.habits
  for delete
  using (auth.uid() = user_id);

drop policy if exists "reminders_select_own" on public.reminders;
drop policy if exists "reminders_insert_own" on public.reminders;
drop policy if exists "reminders_update_own" on public.reminders;
drop policy if exists "reminders_delete_own" on public.reminders;

create policy "reminders_select_own"
  on public.reminders
  for select
  using (auth.uid() = user_id);

create policy "reminders_insert_own"
  on public.reminders
  for insert
  with check (auth.uid() = user_id);

create policy "reminders_update_own"
  on public.reminders
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "reminders_delete_own"
  on public.reminders
  for delete
  using (auth.uid() = user_id);
